src/YoYoCms.AbpProjectTemplate.Web/Models/Layout/HeaderViewModel.cs
using System.Collections.Generic;
using Abp.Application.Navigation;
using Abp.Localization;
using YoYoCms.AbpProjectTemplate.Sessions.Dto;

namespace YoYoCms.AbpProjectTemplate.Web.Models.Layout
{
    public class HeaderViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }
        
        public IReadOnlyList<LanguageInfo> Languages { get; set; }

        public LanguageInfo CurrentLanguage { get; set; }
        
        public UserMenu Menu { get; set; }
        
        public string CurrentPageName { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public bool TenantRegistrationEnabled { get; set; }

        public string GetShownLoginName()
        {
            if (!IsMultiTenancyEnabled)
            {
                return LoginInformations.User.UserName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + LoginInformations.User.UserName
                : LoginInformations.Tenant.TenancyName + "\\" + LoginInformations.User.UserName;
        }


    }
}

src/YoYoCms.AbpProjectTemplate.Web/Controllers/ApplicationController.cs
using System.Web.Mvc;
using Abp.Auditing;
using Abp.Web.Mvc.Authorization;

namespace YoYoCms.AbpProjectTemplate.Web.Controllers
{
   
    public class ApplicationController : AbpProjectTemplateControllerBase
    {
       

        /// <summary>
        /// 管理端Vue项目首页
        /// </summary>
        /// <returns></returns>
        [DisableAuditing]
        public ActionResult Vue()
        {
           
            return File(System.IO.File.Open(Server.MapPath("/Assets/dist/index.html"), System.IO.FileMode.Open), "text/html");
        }


    }
}

src/YoYoCms.AbpProjectTemplate.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using YoYoCms.AbpProjectTemplate.Configuration;
using YoYoCms.AbpProjectTemplate.Sessions;
using YoYoCms.AbpProjectTemplate.Web.Models.Layout;
using YoYoCms.AbpProjectTemplate.Web.Navigation;

namespace YoYoCms.AbpProjectTemplate.Web.Controllers
{
    /// <summary>
    /// Layout for 'front end' pages.
    /// </summary>
    public class LayoutController : AbpProjectTemplateControllerBase
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            ISessionAppService sessionAppService, 
            IUserNavigationManager userNavigationManager, 
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _sessionAppService = sessionAppService;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult Header(string currentPageName = "")
        {
            var headerModel = new HeaderViewModel();
            
            if (AbpSession.UserId.HasValue)
            {
                headerModel.LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations());
            }

            headerModel.Languages = _languageManager.GetLanguages();
            headerModel.CurrentLanguage = _languageManager.CurrentLanguage;
            
            headerModel.Menu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync(FrontEndNavigationProvider.MenuName, AbpSession.ToUserIdentifier()));
            headerModel.CurrentPageName = currentPageName;

            headerModel.IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled;
            headerModel.TenantRegistrationEnabled = SettingManager.GetSettingValue<bool>(AppSettings.TenantManagement.AllowSelfRegistration);

            return PartialView("~/Views/Layout/_Header.cshtml", headerModel);
        }
    }
}

src/YoYoCms.AbpProjectTemplate.Web/Controllers/TenantRegistrationController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Abp.Authorization.Users;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Domain.Uow;
using Abp.UI;
using Abp.Zero.Configuration;
using YoYoCms.AbpProjectTemplate.Configuration;
using YoYoCms.AbpProjectTemplate.Debugging;
using YoYoCms.AbpProjectTemplate.Web.Models.TenantRegistration;
using Abp.Extensions;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using YoYoCms.AbpProjectTemplate.Authorization;
using YoYoCms.AbpProjectTemplate.Editions;
using YoYoCms.AbpProjectTemplate.MultiTenancy;
using YoYoCms.AbpProjectTemplate.Notifications;
using YoYoCms.AbpProjectTemplate.UserManagement.Users;
using YoYoCms.AbpProjectTemplate.Web.Authorization;

namespace YoYoCms.AbpProjectTemplate.Web.Controllers
{
    public class TenantRegistrationController : AbpProjectTemplateControllerBase
    {
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly TenantManager _tenantManager;
        private readonly UserManager _userManager;
        private readonly LogInManager _logInManager;
        private readonly EditionManager _editionManager;
        private readonly IAppNotifier _appNotifier;
        private readonly AbpLoginResultTypeHelper _abpLoginResultTypeHelper;

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public TenantRegistrationController(
            IMultiTenancyConfig multiTenancyConfig,
            TenantManager tenantManager,
            EditionManager editionManager,
            IAppNotifier appNotifier,
            UserManager userManager,
            AbpLoginResultTypeHelper abpLoginResultTypeHelper,
            LogInManager logInManager)
        {
            _multiTenancyConfig = multiTenancyConfig;
            _tenantManager = tenantManager;
            _editionManager = editionManager;
            _appNotifier = appNotifier;
            _userManager = userManager;
            _abpLoginResultTypeHelper = abpLoginResultTypeHelper;
            _logInManager = logInManager;
        }

        public ActionResult Index()
        {
            CheckTenantRegistrationIsEnabled();

            ViewBag.UseCaptcha = UseCaptchaOnRegistration();
            ViewBag.PasswordComplexitySetting = SettingManager.GetSettingValue(AppSettings.Security.PasswordComplexity).Replace("\"","");

            return View();
        }

        [HttpPost]
        [UnitOfWork]
        public virtual async Task<ActionResult> Register(TenantRegistrationViewModel model)
        {
            try
            {
                CheckTenantRegistrationIsEnabled();

                if (UseCaptchaOnRegistration())
                {
                    if (model.Captcha.IsNullOrWhiteSpace())
                    {
                        throw new UserFriendlyException(L("CaptchaCanNotBeEmpty"));
                    }

                    var result = VerifyTheCaptcha(model.Captcha);
                    if (result)
                    {
                        return Json(true);
                    }
                    throw new UserFriendlyException(L("IncorrectCaptchaAnswer"));
                    //todo:租户注册的时候需要验证码
                    //var recaptchaHelper = this.GetRecaptchaVerificationHelper();
                    //if (recaptchaHelper.Response.IsNullOrEmpty())
                    //{
                    //    throw new UserFriendlyException(L("CaptchaCanNotBeEmpty"));
                    //}

                    //if (recaptchaHelper.VerifyRecaptchaResponse() != RecaptchaVerificationResult.Success)
                    //{
                    //    throw new UserFriendlyException(L("IncorrectCaptchaAnswer"));
                    //}
                }

                //Getting host-specific settings
                var isNewRegisteredTenantActiveByDefault = await SettingManager.GetSettingValueForApplicationAsync<bool>(AppSettings.TenantManagement.IsNewRegisteredTenantActiveByDefault);
                var isEmailConfirmationRequiredForLogin = await SettingManager.GetSettingValueForApplicationAsync<bool>(AbpZeroSettingNames.UserManagement.IsEmailConfirmationRequiredForLogin);
                var defaultEditionIdValue = await SettingManager.GetSettingValueForApplicationAsync(AppSettings.TenantManagement.DefaultEdition);
                int? defaultEditionId = null;

                if (!string.IsNullOrEmpty(defaultEditionIdValue) && (await _editionManager.FindByIdAsync(Convert.ToInt32(defaultEditionIdValue)) != null))
                {
                    defaultEditionId = Convert.ToInt32(defaultEditionIdValue);
                }

                CurrentUnitOfWork.SetTenantId(null);

                var tenantId = await _tenantManager.CreateWithAdminUserAsync(
                  model.TenancyName,
                  model.Name,
                  model.AdminPassword,
                  model.AdminEmailAddress,
                  null,
                  isNewRegisteredTenantActiveByDefault,
                  defaultEditionId,
                  false,
                  true);

                ViewBag.UseCaptcha = UseCaptchaOnRegistration();

                var tenant = await _tenantManager.GetByIdAsync(tenantId);
                await _appNotifier.NewTenantRegisteredAsync(tenant);

                CurrentUnitOfWork.SetTenantId(tenant.Id);

                var user = await _userManager.FindByNameAsync(UserManagement.Users.User.AdminUserName);

                //Directly login if possible
                if (tenant.IsActive && user.IsActive && (user.IsEmailConfirmed || !isEmailConfirmationRequiredForLogin))
                {
                    var loginResult = await GetLoginResultAsync(user.UserName, model.AdminPassword, tenant.TenancyName);

                    if (loginResult.Result == AbpLoginResultType.Success)
                    {
                        await SignInAsync(loginResult.User, loginResult.Identity);
                        return Redirect(Url.Action("Index", "Application"));
                    }

                    Logger.Warn("New registered user could not be login. This should not be normally. login result: " + loginResult.Result);
                }

                return View("RegisterResult", new TenantRegisterResultViewModel
                {
                    TenancyName = model.TenancyName,
                    Name = model.Name,
                    UserName = UserManagement.Users.User.AdminUserName,
                    EmailAddress = model.AdminEmailAddress,
                    IsActive = isNewRegisteredTenantActiveByDefault,
                    IsEmailConfirmationRequired = isEmailConfirmationRequiredForLogin
                });
            }
            catch (UserFriendlyException ex)
            {
                ViewBag.UseCaptcha = UseCaptchaOnRegistration();
                ViewBag.ErrorMessage = ex.Message;

                return View("Index", model);
            }
        }

        private bool IsSelfRegistrationEnabled()
        {
            return SettingManager.GetSettingValueForApplication<bool>(AppSettings.TenantManagement.AllowSelfRegistration);
        }

        private void CheckTenantRegistrationIsEnabled()
        {
            if (!IsSelfRegistrationEnabled())
            {
                throw new UserFriendlyException(L("SelfTenantRegistrationIsDisabledMessage_Detail"));
            }

            if (!_multiTenancyConfig.IsEnabled)
            {
                throw new UserFriendlyException(L("MultiTenancyIsNotEnabled"));
            }
        }

        private bool UseCaptchaOnRegistration()
        {
            if (DebugHelper.IsDebug)
            {
                return false;
            }

            return SettingManager.GetSettingValueForApplication<bool>(AppSettings.TenantManagement.UseCaptchaOnRegistration);
        }

        private async Task<AbpLoginResult<Tenant, User>> GetLoginResultAsync(string usernameOrEmailAddress, string password, string tenancyName)
        {
            var loginResult = await _logInManager.LoginAsync(usernameOrEmailAddress, password, tenancyName);

            switch (loginResult.Result)
            {
                case AbpLoginResultType.Success:
                    return loginResult;
                default:
                    throw _abpLoginResultTypeHelper.CreateExceptionForFailedLoginAttempt(loginResult.Result, usernameOrEmailAddress, tenancyName);
            }
        }

        private async Task SignInAsync(User user, ClaimsIdentity identity = null, bool rememberMe = false)
        {
            if (identity == null)
            {
                identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
            }

            AuthenticationManager.SignOutAllAndSignIn(identity, rememberMe);
        }
    }
}

src/YoYoCms.AbpProjectTemplate.Web/Views/Layout/_Footer.cshtml
@using Abp.Timing
    

<footer id="footer" class="footer-light">
    @*<div class="footer-content">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <!-- Footer widget area 1 -->
                    <div class="widget clearfix widget-contact-us" style="background-image: url('images/world-map-dark.png'); background-position: 50% 20px; background-repeat: no-repeat">
                        <h4>About YOYOCMS</h4>
                        <ul class="list-icon">
                            <li><i class="fa fa-map-marker"></i> 795 Folsom Ave, Suite 600
                                <br>San Francisco, CA 94107</li>
                            <li><i class="fa fa-phone"></i> (123) 456-7890 </li>
                            <li><i class="fa fa-envelope"></i> <a href="mailto:first.last@example.com">first.last@example.com</a>
                            </li>
                            <li>
                                <br><i class="fa fa-clock-o"></i>Monday - Friday: <strong>08:00 - 22:00</strong>
                                <br>Saturday, Sunday: <strong>Closed</strong>
                            </li>
                        </ul>
                        <!-- Social icons -->
                        <div class="social-icons social-icons-border float-left m-t-20">
                            <ul>
                                <li class="social-rss"><a href="#"><i class="fa fa-rss"></i></a></li>
                                <li class="social-facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li class="social-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li class="social-vimeo"><a href="#"><i class="fa fa-vimeo"></i></a></li>
                                <li class="social-youtube"><a href="#"><i class="fa fa-youtube"></i></a></li>
                                <li class="social-pinterest"><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                <li class="social-gplus"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <!-- end: Social icons -->
                    </div>
                    <!-- end: Footer widget area 1 -->
                </div>
                <div class="col-md-2">
                    <!-- Footer widget area 2 -->
                    <div class="widget">
                        <h4>Quick LInks</h4>
                        <ul class="list-icon list-icon-arrow">
                            <li><a href="#">About</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Portfolio</a></li>
                            <li><a href="#">Shortcodes</a></li>
                        </ul>
                    </div>
                    <!-- end: Footer widget area 2 -->
                </div>
                <div class="col-md-3">
                    <!-- Footer widget area 3 -->
                    <div class="widget">
                        <h4>Latest From Our Blog</h4>
                        <div class="post-thumbnail-list">
                            <div class="post-thumbnail-entry">

                                <div class="post-thumbnail-content">
                                    <a href="#">Suspendisse consectetur fringilla luctus</a>
                                    <span class="post-date"><i class="fa fa-clock-o"></i> 6m ago</span>
                                    <span class="post-category"><i class="fa fa-tag"></i> Technology</span>
                                </div>
                            </div>
                            <div class="post-thumbnail-entry">

                                <div class="post-thumbnail-content">
                                    <a href="#">Consectetur adipiscing elit</a>
                                    <span class="post-date"><i class="fa fa-clock-o"></i> 24h ago</span>
                                    <span class="post-category"><i class="fa fa-tag"></i> Lifestyle</span>
                                </div>
                            </div>
                            <div class="post-thumbnail-entry">

                                <div class="post-thumbnail-content">
                                    <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>
                                    <span class="post-date"><i class="fa fa-clock-o"></i> 11h ago</span>
                                    <span class="post-category"><i class="fa fa-tag"></i> Lifestyle</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end: Footer widget area 3 -->
                </div>
             <div class="col-md-3">
                    <!-- Footer widget area 4 -->
                    <div class="widget widget-tweeter" data-username="ardianmusliu" data-limit="2">
                        <h4>Recent Tweets</h4>
                    </div>
                    <!-- end: Footer widget area 4 -->
                </div> 
            </div>
        </div>
    </div>*@
    <div class="copyright-content">
        <div class="container">
     
            <div class="copyright-text text-center">&copy; @Clock.Now.Year © YOYOCMS. ALL Rights Reserved. 
            </div>
        </div>
    </div>
</footer>

src/YoYoCms.AbpProjectTemplate.Web/Views/Layout/_Header.cshtml
@using Abp.Application.Navigation
@using Abp.Collections.Extensions
@using Abp.Extensions
@using YoYoCms.AbpProjectTemplate.Web.Views
@model YoYoCms.AbpProjectTemplate.Web.Models.Layout.HeaderViewModel
@helper ShowMenuItemRecursively(UserMenuItem menuItem, int currentLevel)
{
    <li class="@( menuItem.Name == Model.CurrentPageName ? "active" : "") @( menuItem.Items.IsNullOrEmpty() ? "" : (currentLevel == 0 ? "dropdown" : "dropdown-submenu"))">
        @if (menuItem.Items.IsNullOrEmpty())
        {
            if (!menuItem.Url.IsNullOrEmpty())
            {
                <a href="@( UrlChecker.IsRooted(menuItem.Url) ? menuItem.Url : ApplicationPath + menuItem.Url)">@menuItem.DisplayName</a>
            }
            else
            {
                <a href="@ApplicationPath">@menuItem.DisplayName</a>
            }
        }
        else
        {
            <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">
                @menuItem.DisplayName
            </a>
            <ul class="dropdown-menu">
                @foreach (var childMenuItem in menuItem.Items)
                {
                    @ShowMenuItemRecursively(childMenuItem, currentLevel + 1)
                }
            </ul>
        }
    </li>
}

<header id="header" class="header-transparent header-fullwidth">

    <div id="header-wrap">


        <div class="container">
            <!--Logo-->
            <div id="logo">
                <a href="/" class="logo" data-dark-logo="~/Common/Images/app-logo-on-dark.png">
                    <img src="~/Common/Images/app-logo-on-light.png" alt="YoYoCMS Logo">
                </a>
            </div>
            <!--End: Logo-->

            <!--Header Extras-->
            <div class="header-extras">
                <ul>

                    @*<li class="hidden-xs">
                    <!--shopping cart-->
                    <div id="shopping-cart">
                        <a href="shop-cart.html">
                            <span class="shopping-cart-items">8</span>

                            <i class="fa fa-shopping-cart"></i></a>
                    </div>
                    <!--end: shopping cart-->
                </li>*@

                    @if (Model.Languages.Count > 1)
                    {
                        <li>
                            <div id="LanguageDropDown" class="btn-group dropdown">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-delay="1000" data-close-others="true">
                                    <i class="@Model.CurrentLanguage.Icon"></i> @Model.CurrentLanguage.DisplayName <i class="fa fa-angle-down"></i>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    @foreach (var language in Model.Languages)
                                    {
                                        if (Model.CurrentLanguage.Name == language.Name)
                                        {
                                            continue;
                                        }

                                        <li class="language-menu-item">
                                            <a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@Request.Path">
                                                <i class="@language.Icon"></i> <span>@language.DisplayName</span>
                                            </a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </li>
                    }
                    @if (Model.LoginInformations == null && Model.IsMultiTenancyEnabled && Model.TenantRegistrationEnabled)
                    {
                        <li>
                            <a href="@Url.Action("Index", "TenantRegistration")">@L("NewTenant")</a>
                        </li>
                    }
                    <li>
                        @if (Model.LoginInformations != null)
                        {
                            <a href="@Url.Action("dashboard", "view")">@Model.GetShownLoginName() (@L("GoToApplication"))</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Vue", "Application")">@L("LogIn")</a>
                        }
                    </li>
                    <li>
                        @*<div class="topbar-dropdown">
                        <a class="title"><i class="fa fa-globe"></i></a>
                        <div class="dropdown-list">
                            <a class="list-entry" href="#">French</a>
                            <a class="list-entry" href="#">Spanish</a>
                        </div>
                    </div>*@
                    </li>
                </ul>
            </div>
            <!--end: Header Extras-->

            <!--Navigation Resposnive Trigger-->
            <div id="mainMenu-trigger">
                <button class="lines-button x">
                    <span class="lines"></span>
                </button>
            </div>
            <!--end: Navigation Resposnive Trigger-->

            <!--Navigation-->
            <div id="mainMenu" class="light">
                <div class="container">
                    <nav>
                        <ul>
                            @foreach (var menuItem in Model.Menu.Items)
                            {
                                @ShowMenuItemRecursively(menuItem, 0)
                            }
                        </ul>

                    </nav>
                </div>
            </div>
            <!--end: Navigation-->


        </div>
    </div>
</header>

src/YoYoCms.AbpProjectTemplate.Web/Views/Layout/_Layout.cshtml
@using System.Web.Optimization
@using Abp.Web.Mvc.Extensions
@using YoYoCms.AbpProjectTemplate.Localization
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" dir=@(CultureHelper.IsRtl ? "rtl" : "")>
<!--<![endif]-->
<head>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,800,700,600|Montserrat:400,500,600,700|Raleway:100,300,600,700,800" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Poppins:400" rel="stylesheet" property="stylesheet" type="text/css" media="all">

    <title>YoYoCMS-模板网站门户首页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    @* Fill these meta tags upon your project specification *@
    <meta content="YoYoCMS-模板网站门户首页" name="description">
    <meta content="YoYoCMS-模板网站门户首页" name="keywords">
    <meta content="YoYoCMS-模板网站门户首页" name="author">
    <link href="~/polo/css/plugins.css" rel="stylesheet" />
    <link href="~/polo/css/responsive.css" rel="stylesheet" />
    <link href="~/polo/css/style.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/favicon.ico">
    <link href="~/polo/js/plugins/revolution/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css" rel="stylesheet" />
    <link href="~/polo/js/plugins/revolution/fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/polo/js/plugins/revolution/css/settings.css" rel="stylesheet" />
    
    
    

    <link href="~/libs/sweetalert/sweet-alert.css" rel="stylesheet" />
    <link href="~/libs/toastr/toastr.min.css" rel="stylesheet" />
    @RenderSection("Styles", false)
    <!-- REVOLUTION LAYERS STYLES -->
    <style type="text/css">.blurslider-gradient{background:-webkit-linear-gradient(left,#9357cc 0%,#2989d8 50%,#2cc99d 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.blurslider-button{background:-webkit-linear-gradient(left,#9357cc 0%,#2989d8 50%,#2cc99d 100%)}</style>
	

    @Styles.Render("~/Bundles/Common/css")

 
    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/jquery.themepunch.revolution.min.js"></script>
    <link href="~/polo/js/plugins/revolution/revolution-addons/particles/css/revolution.addon.particles.css?ver=1.0.3" rel="stylesheet"/>
    <script type='text/javascript' src='~/polo/js/plugins/revolution/revolution-addons/particles/js/revolution.addon.particles.min.js?ver=1.0.3'></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="~/polo/js/plugins/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script type="text/javascript">
        @* This is used to get the application's root path from javascript.
        It's useful if you're running application in a virtual directory under IIS. *@
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

</head>
<body >
<div id="wrapper">
    @Html.Action("Header", "Layout", new {currentPageName = ViewBag.CurrentPageName})

             @RenderBody()
  
    @Html.Partial("~/Views/Layout/_Footer.cshtml")
</div>
<!-- Go to top button -->
<a id="goToTop"><i class="fa fa-angle-up top-icon"></i><i class="fa fa-angle-up"></i></a>
<!--[if lt IE 9]>
    <script src="~/libs/respond/respond.min.js"></script>
<![endif]-->




<script src="~/libs/sweetalert/sweet-alert.min.js"></script>
<script src="~/libs/toastr/toastr.min.js"></script>
@Scripts.Render("~/Bundles/Frontend/libs/js")

<script type="text/javascript">
    abp.localization.defaultSourceName = '@LocalizationSourceName';
</script>

<!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
<script src="~/AbpScripts/GetScripts" type="text/javascript"></script>


@Scripts.Render("~/Bundles/Common/js")
<script src="~/polo/js/plugins.js"></script>

<script src="~/polo/js/functions.js"></script>
 

@RenderSection("Scripts", false)

</body>

</html>